site_name: ExpressLRS.RU
repo_url: https://github.com/ExpressLRS/ExpressLRS/releases/
repo_name: ExpressLRS
theme:
  name: material
  features:
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.instant
  - toc.follow
  - navigation.path
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  language: ru
  logo: assets/images/logotype.svg
  favicon: favicon.ico
  
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: default
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
    primary: teal
    accent: blue
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
    primary: teal
    accent: lime   
markdown_extensions:
  - pymdownx.details
  - toc:
      permalink: true
  - admonition
  - attr_list
  - md_in_html

#Добавлять новые пункты через тут, названия заданные тут видны на сайте, названия файлов - структура ссылки#
nav:
 - Инструкции: 
    - Прошивка:
      - Передатчики:
        - Внешние передатчики: Manuals/Firmware/Transmitters/ExternalTX/Flashing-external-tx.md
        - Внутренние передатчики: Manuals/Firmware/Transmitters/InternalTX/index.md
    - Параметры сборки: Manuals/FlashingOptions.md